{% set name = "django-codemirror6" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-codemirror6-{{ version }}.tar.gz
  sha256: 47881f7dfaf0e082780c3fd5ee957d173bd37616c63332041605e9618a11216b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django

test:
  imports:
    - django_codemirror6
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/grantjenks/django-codemirror6
  summary: Django CodeMirror 6
  dev_url: https://github.com/grantjenks/django-codemirror6
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
